# this line is for copy-pasters...
#         ...while you are removing my credit and calling yourself a developerr... 
#         _____ just imagine, At that time i am fucking your mom and sis at same time, harder & too harder...
#
# Credit @user_is_leo.
# Please Don't remove credit.
# Born to make history @LazyDeveloper !
# for any error please contact me -> telegram@leotgadmin_bot